config/urls.py
from django.contrib import admin
from django.urls import path, include
from pybo.views import base_views
from django.conf import settings
from django.conf.urls.static import static


urlpatterns = [
    path('admin/', admin.site.urls),
    path('pybo/', include('pybo.urls')),
    # path('paystub/', include('paystub.urls')),
    path('common/', include('common.urls')),
    path('polls/', include('polls.urls')),
    path('eas/', include('eas.urls')),
    path('pybo/', base_views.index),
    path('', include('polls.urls')),
    path('eos/', include('eos.urls')),
    path('cart/', include('cart.urls')),
    # 👉 전자 품의서
    path('approval/', include('approvals.urls')),
    
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

eas/urls.py
# eas/urls.py
from django.urls import path
from . import views
from django.conf.urls.static import static
from django.conf import settings

app_name = "eas"

urlpatterns = [
    path("", views.index, name="index"),
    path("<int:Request_id>/", views.detail, name="detail_r"),

    # (주의) detail은 Request_id 인자가 필요한 detail 뷰와 시그니처가 안 맞을 수 있어.
    # 필요 없으면 지우는 걸 추천. 일단 유지하려면 detail 뷰를 따로 만들거나 URL을 없애야 함.
    # path("detail", views.detail, name="detail"),

    path("Request/create/", views.Request_create, name="Request_create"),
    path("Request/create_24/", views.Request_create_24, name="Request_create_24"),
    path("Request/create/sangsin/<int:new_Request_id>/", views.Request_create_sangsin, name="Request_create_sangsin"),

    path("detail/update/<int:new_Request_id>/", views.detail_update, name="detail_update"),
    path("detail/okupdate/<int:new_Request_id>/", views.detail_okupdate, name="detail_okupdate"),
    path("detail/update2/<int:new_Request_id>/", views.detail_update2, name="detail_update2"),
    path("detail/okupdate2/<int:new_Request_id>/", views.detail_okupdate2, name="detail_okupdate2"),

    path("detail_modify/<int:new_Request_id>/", views.Request_modify, name="Request_modify"),

    path("monthly_holiday/", views.monthly_holiday, name="monthly_holiday"),
    path("monthly_holiday_r/<int:Request_id>/", views.monthly_holiday_r, name="monthly_holiday_r"),
    path("monthly_holiday_r/okupdate2/<int:new_Request_id>/", views.monthly_holiday_r_okupdate2, name="monthly_holiday_r_okupdate2"),
    path("monthly_holiday_r/update2/<int:new_Request_id>/", views.monthly_holiday_r_update2, name="monthly_holiday_r_update2"),

    path("account.html/", views.account, name="account"),

    path("nomal_approval/", views.nomal_approval, name="nomal_approval"),
    path("nomal_approval_r/<int:Request_id>/", views.nomal_approval_r, name="nomal_approval_r"),

    path("ds.html/", views.ds, name="ds"),

    # ✅ 자동완성 API
    path("api/vendor-suggest/", views.vendor_suggest, name="vendor_suggest"),
]

urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

eos/urls.py
from django.urls import path
from . import views
from django.conf.urls.static import static
from django.conf import settings
from .views import ProductView

app_name = 'eos'

urlpatterns = [
    path('', views.index, name='index'),
    path('<int:Order_list_id>/', views.order_page, name='order_page'),
    path('<int:User_id>/', views.order_page, name='order_page'),
    path('product/', ProductView.as_view(), name='product'),
    path('p_list/', views.p_list),
    path('order_page/', views.order_page, name='order_page'),
    path('order_create/', views.order_create, name='order_create'),
    path('order_create/searchData/', views.searchData, name='searchData'),

]

polls/urls.py
from django.urls import path
from . import views

app_name = 'polls'

urlpatterns = [
    # path('', views.index, name='index'),
    # ex: /polls/5
    # path('<int:question_id>/', views.detail, name='detail'),
    # # ex: /polls/5/results/
    # path('<int:question_id>/results/', views.results, name='results'),
    # # ex: /polls/5/vote/
    # path('<int:question_id>/vote/', views.vote, name='vote'),
]

pybo/urls.py
from django.urls import path

from .views import base_views, question_views, answer_views, comment_views, vote_views

app_name = 'pybo'

urlpatterns = [
    # base_views.py
    path('pybo/',
         base_views.index, name='index'),
    path('<int:question_id>/',
         base_views.detail, name='detail'),

    # question_views.py
    path('question/create/',
         question_views.question_create, name='question_create'),
    path('question/modify/<int:question_id>/',
         question_views.question_modify, name='question_modify'),
    path('question/delete/<int:question_id>/',
         question_views.question_delete, name='question_delete'),

    # answer_views.py
    path('answer/create/<int:question_id>/',
         answer_views.answer_create, name='answer_create'),
    path('answer/modify/<int:answer_id>/',
         answer_views.answer_modify, name='answer_modify'),
    path('answer/delete/<int:answer_id>/',
         answer_views.answer_delete, name='answer_delete'),

    # comment_views.py
    path('comment/create/question/<int:question_id>/',
         comment_views.comment_create_question, name='comment_create_question'),
    path('comment/modify/question/<int:comment_id>/',
         comment_views.comment_modify_question, name='comment_modify_question'),
    path('comment/delete/question/<int:comment_id>/',
         comment_views.comment_delete_question, name='comment_delete_question'),
    path('comment/create/answer/<int:answer_id>/',
         comment_views.comment_create_answer, name='comment_create_answer'),
    path('comment/modify/answer/<int:comment_id>/',
         comment_views.comment_modify_answer, name='comment_modify_answer'),
    path('comment/delete/answer/<int:comment_id>/',
         comment_views.comment_delete_answer, name='comment_delete_answer'),
# vote_views.py
    path('vote/question/<int:question_id>/', vote_views.vote_question, name='vote_question'),
    path('vote/answer/<int:answer_id>/', vote_views.vote_answer, name='vote_answer'),

]

polls/models.py
from django.db import models

# Create your models here.

class Question(models.Model):
    question_text = models.CharField(max_length=200)
    pub_date = models.DateTimeField('date published')
    def __str__(self):
        return self.question_text

class Chioce(models.Model):
    question = models.ForeignKey(Question, on_delete=models.CASCADE)
    choice_text = models.CharField(max_length=200)
    votes = models.IntegerField(default=0)
    def __str__(self):
        return self.choice_text

polls/views.py
from django.template import loader
from django.http import HttpResponse, HttpResponseRedirect
from .models import Question
from django.shortcuts import get_object_or_404, render
from django.urls import reverse
from .models import Chioce, Question

def index(request):
    latest_question_list = Question.objects.order_by('-pub_date')[:5]
    template = loader.get_template('polls/index.html')
    context = {
        'latest_question_list': latest_question_list,
    }
    # return HttpResponse(template.render(context, request)) 아래 render 사용하면 똑같다.
    return render(request, 'polls/index.html', context)


def detail(request, question_id):
    question = get_object_or_404(Question, pk=question_id)
    return render(request, 'polls/detail.html', {'question': question})

def results(request, question_id):
    question = get_object_or_404(Question, pk=question_id)
    return render(request, 'polls/results.html', {'question': question})

def vote(request, question_id):
    question = get_object_or_404(Question, pk=question_id)
    try:
        select_chioce = question.chioce_set.get(pk=request.POST['chioce'])
    except(KeyError, Chioce.DoesNotExist):
        return render(request, 'polls/detail.html', {
            'question': question,
            'error_message': "You didn't select a choice.",
        })
    else:
        select_chioce.votes +=1
        select_chioce.save()
        return HttpResponseRedirect(reverse('polls:results', args=(question_id,)))

polls/templates/polls/detail.html
<h1>{{ question.question_text }}</h1>

{% if error_message %}<p><strong>{{ error_message }}</strong></p>{% endif %}

<form action="{% url 'polls:vote' question.id %}" method="post">
{% csrf_token %}
<!--    아래 포문 모델에서 모델명 쵸이스 스페링 잘못써서 chioce 하고 choice_text 구분 잘해야 ...-->
{% for chioce in question.chioce_set.all %}
    <input type="radio" name="chioce" id="chioce{{ forloop.counter }}" value="{{ chioce.id }}">
    <label for="chioce{{ forloop.counter }}">{{ chioce.choice_text }}</label><br>
{% endfor %}
<input type="submit" value="Vote">
</form>

polls/templates/polls/index.html
<!--{% if latest_question_list %}-->
<!--    <ul>-->
<!--        {% for question in latest_question_list %}-->
<!--            <li><a href="{% url 'polls:detail' question.id %}">{{question.question_text}}</a></li>-->

<!--        {% endfor %}-->
<!--    </ul>-->
<!--{% else %}-->
<!--    <p>No polls are available.</p>-->

<!--{% endif %}-->
<!--위에는 기존 poll index-->

    <!-- Bootstrap CSS -->
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-1BmE4kWBq78iYhFldvKuhfTAU6auU8tT94WrHftjDbrCEXSU1oBoqyl2QvZ6jIW3" crossorigin="anonymous">
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/1.12.4/jquery.min.js"></script>
<div>
<p></p>
<p></p>
<p></p>
</div>
<div class="container my-3">
    <div>
<br>
    <br>
        <br>
        <br>
    <br>
        <br>
</div>
    <div class="row justify-content-between">

        <div class="col-lg-4" align="middle" style="margin:auto">
            <a type="button" class="btn btn-sm btn-outline-danger" href="{% url 'eas:index' %}"><b> e a s</b></a>
        </div>

        <div class="col-lg-4">
                <img src="/static/img/dj_bi.png" class="img-fluid" alt="...">
        </div>

        <div class="col-lg-4" align="middle" style="margin:auto">
            <a type="button" class="btn btn-sm btn-outline-success" href="{% url 'eos:index' %}"><b> e o s</b> </a>
             <a type="button" class="btn btn-sm btn-outline-primary" href="{% url 'pybo:index' %}"> board </a>
        </div>


    </div>

</div>

polls/templates/polls/results.html
<h1>{{ question.question_text }}</h1>

<ul>
{% for chioce in question.chioce_set.all %}
    <li>{{ chioce.choice_text }} -- {{ chioce.votes }} vote{{ chioce.votes|pluralize }}</li>
{% endfor %}
</ul>

<a href="{% url 'polls:detail' question.id %}">Vote again?</a>