common/urls.py
from django.urls import path, include
from django.contrib.auth import views as auth_views
from . import views

app_name = 'common'

urlpatterns = [
    path('login/', auth_views.LoginView.as_view(template_name='common/login.html'), name='login'),
    path('logout/', auth_views.LogoutView.as_view(), name='logout'),
    path('signup/', views.signup, name='signup'),
]

config/urls.py
from django.contrib import admin
from django.urls import path, include
from pybo.views import base_views
from django.conf import settings
from django.conf.urls.static import static


urlpatterns = [
    path('admin/', admin.site.urls),
    path('pybo/', include('pybo.urls')),
    # path('paystub/', include('paystub.urls')),
    path('common/', include('common.urls')),
    path('polls/', include('polls.urls')),
    path('eas/', include('eas.urls')),
    path('pybo/', base_views.index),
    path('', include('polls.urls')),
    path('eos/', include('eos.urls')),
    path('cart/', include('cart.urls')),
    # 👉 전자 품의서
    path('approval/', include('approvals.urls')),
    
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

eas/urls.py
# eas/urls.py
from django.urls import path
from . import views
from django.conf.urls.static import static
from django.conf import settings

app_name = "eas"

urlpatterns = [
    path("", views.index, name="index"),
    path("<int:Request_id>/", views.detail, name="detail_r"),

    # (주의) detail은 Request_id 인자가 필요한 detail 뷰와 시그니처가 안 맞을 수 있어.
    # 필요 없으면 지우는 걸 추천. 일단 유지하려면 detail 뷰를 따로 만들거나 URL을 없애야 함.
    # path("detail", views.detail, name="detail"),

    path("Request/create/", views.Request_create, name="Request_create"),
    path("Request/create_24/", views.Request_create_24, name="Request_create_24"),
    path("Request/create/sangsin/<int:new_Request_id>/", views.Request_create_sangsin, name="Request_create_sangsin"),

    path("detail/update/<int:new_Request_id>/", views.detail_update, name="detail_update"),
    path("detail/okupdate/<int:new_Request_id>/", views.detail_okupdate, name="detail_okupdate"),
    path("detail/update2/<int:new_Request_id>/", views.detail_update2, name="detail_update2"),
    path("detail/okupdate2/<int:new_Request_id>/", views.detail_okupdate2, name="detail_okupdate2"),

    path("detail_modify/<int:new_Request_id>/", views.Request_modify, name="Request_modify"),

    path("monthly_holiday/", views.monthly_holiday, name="monthly_holiday"),
    path("monthly_holiday_r/<int:Request_id>/", views.monthly_holiday_r, name="monthly_holiday_r"),
    path("monthly_holiday_r/okupdate2/<int:new_Request_id>/", views.monthly_holiday_r_okupdate2, name="monthly_holiday_r_okupdate2"),
    path("monthly_holiday_r/update2/<int:new_Request_id>/", views.monthly_holiday_r_update2, name="monthly_holiday_r_update2"),

    path("account.html/", views.account, name="account"),

    path("nomal_approval/", views.nomal_approval, name="nomal_approval"),
    path("nomal_approval_r/<int:Request_id>/", views.nomal_approval_r, name="nomal_approval_r"),

    path("ds.html/", views.ds, name="ds"),

    # ✅ 자동완성 API
    path("api/vendor-suggest/", views.vendor_suggest, name="vendor_suggest"),
]

urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

eos/urls.py
from django.urls import path
from . import views
from django.conf.urls.static import static
from django.conf import settings
from .views import ProductView

app_name = 'eos'

urlpatterns = [
    path('', views.index, name='index'),
    path('<int:Order_list_id>/', views.order_page, name='order_page'),
    path('<int:User_id>/', views.order_page, name='order_page'),
    path('product/', ProductView.as_view(), name='product'),
    path('p_list/', views.p_list),
    path('order_page/', views.order_page, name='order_page'),
    path('order_create/', views.order_create, name='order_create'),
    path('order_create/searchData/', views.searchData, name='searchData'),

]

pybo/urls.py
from django.urls import path

from .views import base_views, question_views, answer_views, comment_views, vote_views

app_name = 'pybo'

urlpatterns = [
    # base_views.py
    path('pybo/',
         base_views.index, name='index'),
    path('<int:question_id>/',
         base_views.detail, name='detail'),

    # question_views.py
    path('question/create/',
         question_views.question_create, name='question_create'),
    path('question/modify/<int:question_id>/',
         question_views.question_modify, name='question_modify'),
    path('question/delete/<int:question_id>/',
         question_views.question_delete, name='question_delete'),

    # answer_views.py
    path('answer/create/<int:question_id>/',
         answer_views.answer_create, name='answer_create'),
    path('answer/modify/<int:answer_id>/',
         answer_views.answer_modify, name='answer_modify'),
    path('answer/delete/<int:answer_id>/',
         answer_views.answer_delete, name='answer_delete'),

    # comment_views.py
    path('comment/create/question/<int:question_id>/',
         comment_views.comment_create_question, name='comment_create_question'),
    path('comment/modify/question/<int:comment_id>/',
         comment_views.comment_modify_question, name='comment_modify_question'),
    path('comment/delete/question/<int:comment_id>/',
         comment_views.comment_delete_question, name='comment_delete_question'),
    path('comment/create/answer/<int:answer_id>/',
         comment_views.comment_create_answer, name='comment_create_answer'),
    path('comment/modify/answer/<int:comment_id>/',
         comment_views.comment_modify_answer, name='comment_modify_answer'),
    path('comment/delete/answer/<int:comment_id>/',
         comment_views.comment_delete_answer, name='comment_delete_answer'),
# vote_views.py
    path('vote/question/<int:question_id>/', vote_views.vote_question, name='vote_question'),
    path('vote/answer/<int:answer_id>/', vote_views.vote_answer, name='vote_answer'),

]

pybo/views/base_views.py
from pyexpat.errors import messages
from time import timezone

from django.contrib.auth.decorators import login_required
from django.core.paginator import Paginator
from django.shortcuts import render, get_object_or_404, redirect

from ..forms import AnswerForm, QuestionForm, CommentForm
from ..models import Question, Answer, Comment

from django.db.models import Q, Count


def index(request):
    """
        pybo 목록 출력
        """
    # 입력 파라미터
    page = request.GET.get('page', '1')  # 페이지
    kw = request.GET.get('kw', '')  # 검색어
    so = request.GET.get('so', 'recent')  # 정렬기준

    # 정렬
    if so == 'recommend':
        question_list = Question.objects.annotate(num_voter=Count('voter')).order_by('-num_voter', '-create_date')
    elif so == 'popular':
        question_list = Question.objects.annotate(num_answer=Count('answer')).order_by('-num_answer', '-create_date')
    else:  # recent
        question_list = Question.objects.order_by('-create_date')

    # 조회

    if kw:
        question_list = question_list.filter(
            Q(subject__icontains=kw) |  # 제목검색
            Q(content__icontains=kw) |  # 내용검색
            Q(author__username__icontains=kw) |  # 질문 글쓴이검색
            Q(answer__author__username__icontains=kw)  # 답변 글쓴이검색
        ).distinct()

    # 페이징처리
    paginator = Paginator(question_list, 10)  # 페이지당 10개씩 보여주기
    page_obj = paginator.get_page(page)
    context = {'question_list': page_obj, 'page': page, 'kw': kw, 'so': so}
    return render(request, 'pybo/question_list.html', context)


def detail(request, question_id):
    """
    pybo 내용 출력
    """
    question = get_object_or_404(Question, pk=question_id)
    context = {'question': question}
    return render(request, 'pybo/question_detail.html', context)


@login_required(login_url='common:login')
def answer_create(request, question_id):
    """
    pybo 답변등록
    """
    question = get_object_or_404(Question, pk=question_id)
    # question.answer_set.create(content=request.POST.get('content'), create_date=timezone.now())
    # return redirect('pybo:detail', question_id=question.id)

    if request.method == "POST":
        form = AnswerForm(request.POST)
        if form.is_valid():
            answer = form.save(commit=False)
            answer.author = request.user  # author 속성에 로그인 계정 저장
            answer.create_date = timezone.now()
            answer.question = question
            answer.save()
            return redirect('pybo:detail', question_id=question.id)
    else:
        form = AnswerForm()
    context = {'question': question, 'form': form}
    return render(request, 'pybo/question_detail.html', context)


@login_required(login_url='common:login')
def question_create(request):
    """
    pybo 질문등록
    """
    # form = QuestionForm()
    # return render(request, 'pybo/question_form.html', {'form': form})

    if request.method == 'POST':
        form = QuestionForm(request.POST)
        if form.is_valid():
            question = form.save(commit=False)
            question.author = request.user  # author 속성에 로그인 계정 저장
            question.create_date = timezone.now()
            question.save()
            return redirect('pybo:index')
    else:
        form = QuestionForm()
    context = {'form': form}
    return render(request, 'pybo/question_form.html', context)


@login_required(login_url='common:login')
def question_modify(request, question_id):
    """
    pybo 질문수정
    """
    question = get_object_or_404(Question, pk=question_id)
    if request.user != question.author:
        messages.error(request, '수정권한이 없습니다')
        return redirect('pybo:detail', question_id=question.id)

    if request.method == "POST":
        form = QuestionForm(request.POST, instance=question)
        if form.is_valid():
            question = form.save(commit=False)
            question.modify_date = timezone.now()  # 수정일시 저장
            question.save()
            return redirect('pybo:detail', question_id=question.id)
    else:
        form = QuestionForm(instance=question)
    context = {'form': form}
    return render(request, 'pybo/question_form.html', context)


@login_required(login_url='common:login')
def question_delete(request, question_id):
    """
    pybo 질문삭제
    """
    question = get_object_or_404(Question, pk=question_id)
    if request.user != question.author:
        messages.error(request, '삭제권한이 없습니다')
        return redirect('pybo:detail', question_id=question.id)
    question.delete()
    return redirect('pybo:index')


@login_required(login_url='common:login')
def answer_modify(request, answer_id):
    """
    pybo 답변수정
    """
    answer = get_object_or_404(Answer, pk=answer_id)
    if request.user != answer.author:
        messages.error(request, '수정권한이 없습니다')
        return redirect('pybo:detail', question_id=answer.question.id)

    if request.method == "POST":
        form = AnswerForm(request.POST, instance=answer)
        if form.is_valid():
            answer = form.save(commit=False)
            answer.modify_date = timezone.now()
            answer.save()
            return redirect('pybo:detail', question_id=answer.question.id)
    else:
        form = AnswerForm(instance=answer)
    context = {'answer': answer, 'form': form}
    return render(request, 'pybo/answer_form.html', context)


@login_required(login_url='common:login')
def answer_delete(request, answer_id):
    """
    pybo 답변삭제
    """
    answer = get_object_or_404(Answer, pk=answer_id)
    if request.user != answer.author:
        messages.error(request, '삭제권한이 없습니다')
    else:
        answer.delete()
    return redirect('pybo:detail', question_id=answer.question.id)


@login_required(login_url='common:login')
def comment_create_question(request, question_id):
    """
    pybo 질문댓글등록
    """
    question = get_object_or_404(Question, pk=question_id)
    if request.method == "POST":
        form = CommentForm(request.POST)
        if form.is_valid():
            comment = form.save(commit=False)
            comment.author = request.user
            comment.create_date = timezone.now()
            comment.question = question
            comment.save()
            return redirect('pybo:detail', question_id=question.id)
    else:
        form = CommentForm()
    context = {'form': form}
    return render(request, 'pybo/comment_form.html', context)


@login_required(login_url='common:login')
def comment_modify_question(request, comment_id):
    """
    pybo 질문댓글수정
    """
    comment = get_object_or_404(Comment, pk=comment_id)
    if request.user != comment.author:
        messages.error(request, '댓글수정권한이 없습니다')
        return redirect('pybo:detail', question_id=comment.question.id)

    if request.method == "POST":
        form = CommentForm(request.POST, instance=comment)
        if form.is_valid():
            comment = form.save(commit=False)
            comment.modify_date = timezone.now()
            comment.save()
            return redirect('pybo:detail', question_id=comment.question.id)
    else:
        form = CommentForm(instance=comment)
    context = {'form': form}
    return render(request, 'pybo/comment_form.html', context)


@login_required(login_url='common:login')
def comment_delete_question(request, comment_id):
    """
    pybo 질문댓글삭제
    """
    comment = get_object_or_404(Comment, pk=comment_id)
    if request.user != comment.author:
        messages.error(request, '댓글삭제권한이 없습니다')
        return redirect('pybo:detail', question_id=comment.question.id)
    else:
        comment.delete()
    return redirect('pybo:detail', question_id=comment.question.id)


@login_required(login_url='common:login')
def comment_create_answer(request, answer_id):
    """
    pybo 답글댓글등록
    """
    answer = get_object_or_404(Answer, pk=answer_id)
    if request.method == "POST":
        form = CommentForm(request.POST)
        if form.is_valid():
            comment = form.save(commit=False)
            comment.author = request.user
            comment.create_date = timezone.now()
            comment.answer = answer
            comment.save()
            return redirect('pybo:detail', question_id=comment.answer.question.id)
    else:
        form = CommentForm()
    context = {'form': form}
    return render(request, 'pybo/comment_form.html', context)


@login_required(login_url='common:login')
def comment_modify_answer(request, comment_id):
    """
    pybo 답글댓글수정
    """
    comment = get_object_or_404(Comment, pk=comment_id)
    if request.user != comment.author:
        messages.error(request, '댓글수정권한이 없습니다')
        return redirect('pybo:detail', question_id=comment.answer.question.id)

    if request.method == "POST":
        form = CommentForm(request.POST, instance=comment)
        if form.is_valid():
            comment = form.save(commit=False)
            comment.modify_date = timezone.now()
            comment.save()
            return redirect('pybo:detail', question_id=comment.answer.question.id)
    else:
        form = CommentForm(instance=comment)
    context = {'form': form}
    return render(request, 'pybo/comment_form.html', context)


@login_required(login_url='common:login')
def comment_delete_answer(request, comment_id):
    """
    pybo 답글댓글삭제
    """
    comment = get_object_or_404(Comment, pk=comment_id)
    if request.user != comment.author:
        messages.error(request, '댓글삭제권한이 없습니다')
        return redirect('pybo:detail', question_id=comment.answer.question.id)
    else:
        comment.delete()
    return redirect('pybo:detail', question_id=comment.answer.question.id)

templates/base.html
{% load static %}
<!doctype html>
<html lang="ko">
<head>
    <!-- Required meta tags -->
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <!-- Bootstrap CSS -->
    <link rel="stylesheet" type="text/css" href="{% static 'bootstrap.min.css' %}">
    <!-- pybo CSS -->
    <link rel="stylesheet" type="text/css" href="{% static 'style.css' %}">
    <title>daejin board</title>
</head>
<body>

{% include "navbar.html" %}

<!-- 기본 템플릿 안에 삽입될 내용 Start -->
{% block content %}
{% endblock %}
<!-- 기본 템플릿 안에 삽입될 내용 End -->
<!-- jQuery JS -->
<script src="{% static 'jquery-3.6.0.min.js' %}"></script>
<!-- Bootstrap JS -->
<script src="{% static 'bootstrap.min.js' %}"></script>
<!-- 자바스크립트 Start -->
{% block script %}
{% endblock %}
<!-- 자바스크립트 End -->
</body>
</html>

templates/base_eas.html
{% load static %}
<!--<!doctype html>-->
<html lang="ko">
  <head>
      <link rel="shortcut icon" href="{% static 'img/daejindojang.ico' %}">
    <!-- Required meta tags -->
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <!-- Bootstrap CSS -->
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-1BmE4kWBq78iYhFldvKuhfTAU6auU8tT94WrHftjDbrCEXSU1oBoqyl2QvZ6jIW3" crossorigin="anonymous">
<!--    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/js/bootstrap.bundle.min.js" integrity="sha384-ka7Sk0Gln4gmtz2MlQnikT1wXgYsOg+OMhuP+IlRH9sENBO0LRn5q+8nbTov4+1p" crossorigin="anonymous"></script>-->
      <script src="https://ajax.googleapis.com/ajax/libs/jquery/1.12.4/jquery.min.js"></script>


  </head>

  <title>대진산업_전자결재</title>

  <body>
  <!-- 네비게이션바 -->

    <nav class="navbar navbar-expand-lg navbar-dark bg-dark border-bottom" style="height:8%">
        <div class="container-sm">
            <div>
            <a class="navbar-brand" href="{% url 'eas:index' %}" accesskey="j" onMouseOver="this.innerHTML='alt+j'" onMouseOut="this.innerHTML='Eas'">Eas</a>
            <a class="navbar-brand" href="{% url 'eas:Request_create' %}" accesskey="w" onMouseOver="this.innerHTML='alt+w'" onMouseOut="this.innerHTML='write'">write</a>
            <a class="navbar-brand" style="display:none;" href="{% url 'eas:Request_create_24' %}" accesskey="R">write</a>
            <a class="navbar-brand" style="display:none;" href="/hometax" accesskey="h">hometax</a>
            </div>
            <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
              <span class="navbar-toggler-icon"></span>
            </button>
          <div class="navbar-collapse collapse justify-content-end" id="navbarSupportedContent">

<!-- --------------택배조회 -->
            <div class="d-none d-sm-block">
            <form style="padding-top:18px" name="viewerForm" action="http://info.sweettracker.co.kr/tracking/4" method="post" target="viewer" onsubmit="postPopUp();">
                {% csrf_token %}
                <div class="input-group flex-nowrap">
                    <!--                <label for="t_key"></label>-->
                    <input type="hidden" class="form-control form-control-sm" id="t_key" name="t_key" value="huQxmfgXgANLMwhwpq9JjQ">
                    <!--                </div>-->
                    <!--                <div class="form-group">--></div>
                <div class="input-group flex-nowrap">
                    <!--                <label for="t_code">택배사 코드</label>-->
                    <!--                 <input type="text" class="form-control form-control-sm" name="t_code" id="t_code" placeholder="택배사 코드">-->
                    <select class="form-select form-select-sm" aria-label="Default select example" name="t_code"
                            id="t_code" accesskey="t">>
                        <option selected>택배사</option>
                        <option value="04">대한통운</option>
                        <option value="05">한진</option>
                        <option value="08">롯데</option>
                        <option value="06">로젠</option>
                        <option value="23">경동</option>
                        <option value="32">합동</option>
                        <option value="18">건영</option>
                        <option value="17">천일</option>
                        <option value="45">호남</option>
                        <option value="01">우체국</option>
                    </select>
                    &nbsp;
                    <input class="form-control form-control-ml" name="t_invoice" id="t_invoice"
                           oninput="removeNonNumeric()" placeholder="송장 번호">
                    <button type="submit" class="btn btn-outline-secondary">Search</button>
                </div>

            </form>
            </div>
              &nbsp;&nbsp;
<!-- --------------택배조회 끝-->
<!--             <form id="search">-->
               <button class="btn btn-outline-light" type="button" onclick="window.open('http://3.37.211.248/eas/account.html','window_name','width=730,height=195, left=710, top=86, location=no,status=no,scrollbars=yes');" accesskey="q" onMouseOver="this.innerHTML=' ALT+Q '" onMouseOut="this.innerHTML='계좌조회'">계좌조회</button>

<!--             </form>-->

        </div>

       </div>



<!--            <div class="collapse navbar-collapse" id="navbarSupportedContent">-->
<!--                <ul class="navbar-nav me-auto mb-2 mb-lg-0">-->
<!--                    <li class="nav-item">-->
<!--&lt;!&ndash;                        <a class="nav-link" href="#">로그인</a>&ndash;&gt;-->
<!--                    </li>-->
<!--                </ul>-->
<!--            </div>-->


    </nav>

  <!-- 기본 템플릿 안에 삽입될 내용 Start -->
  {% block content %}
  {% endblock %}
  <!-- 기본 템플릿 안에 삽입될 내용 End -->

  <!-- 자바스크립트 Start -->
  {% block script %}
  {% endblock %}
  <!-- 자바스크립트 End -->

<!--  <script>-->
<!--      const searchInput = document.getElementById("search_kw");-->
<!--      const maxLength = 50;-->

<!--      searchInput.addEventListener("focus", e => {-->
<!--      const el = e.target;-->
<!--      setTimeout(() => {-->
<!--        el.setSelectionRange(maxLength, maxLength);-->
<!--        el.scrollLeft = maxLength * 30;-->
<!--        }, 0);-->
<!--      });-->
<!--  </script>-->
  </body>
  <script type="text/javascript">
      function postPopUp(viewerForm) {

        frm = document.getElementById(viewerForm);
        window.open('', 'viewer', 'width=500, height=800 left=710, top=86, location=no,status=no,scrollbars=yes');

       }

<!--      function regExp(t_invoice){-->
<!--      var reg = /[\{\}\[\]\/?.,;:|\)*~`!^\-_+<>@\#$%&\\\=\(\'\"]/gi-->
<!--      //특수문자 검증-->
<!--      if(reg.test(t_invoice)){-->
<!--        //특수문자 제거후 리턴-->
<!--        return t_invoice.replace(reg, "");-->
<!--      } else {-->
<!--        //특수문자가 없으므로 본래 문자 리턴-->
<!--        return str;-->
<!--        }-->
<!--      }-->

<!--     $('body').on('input', 'input[name=t_invoice]', function() {-->
<!--          var reg = /[\{\}\[\]\/?.,;:|\)*~`!^\-_+<>@\#$%&\\\=\(\'\"]/gi-->
<!--          $(this).val($(this).val().replace(reg, ''));-->
<!--          var value = $('input[name=t_invoice]').val();-->
<!--            value = value.replace("-", "");-->
<!--            $('input[name=t_invoice]').val(value);-->
<!--        });-->
<!-- 택배조회 입력창 숫자외 문자 제외 -->
function removeNonNumeric() {
    var input = document.getElementById("t_invoice");
    input.value = input.value.replace(/[^0-9]/g, "");
}

  </script>

</html>

templates/base_eos.html
{% load static %}
<!--<!doctype html>-->
<html lang="ko" xmlns="http://www.w3.org/1999/html">
  <head>
      <link rel="shortcut icon" href="{% static 'img/eos_icon_1.ico' %}">
    <!-- Required meta tags -->
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <!-- Bootstrap CSS -->
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-1BmE4kWBq78iYhFldvKuhfTAU6auU8tT94WrHftjDbrCEXSU1oBoqyl2QvZ6jIW3" crossorigin="anonymous">
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/1.12.4/jquery.min.js"></script>
<!--   아래3줄 달력 cdn-->
        <link rel="stylesheet" href="//code.jquery.com/ui/1.11.4/themes/smoothness/jquery-ui.css">
        <script src="https://code.jquery.com/jquery-3.6.0.min.js"></script>
<!--        <script src="//code.jquery.com/jquery.min.js"></script>-->
        <script src="//code.jquery.com/ui/1.11.4/jquery-ui.min.js"></script>

<!--   달력 cdn 끝-->
<!--      키패드 cdn -->
<!--        <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.1.3/css/bootstrap.min.css" integrity="sha384-MCw98/SFnGE8fJT3GXwEOngsV7Zt27NXFoaoApmYm81iuXoPkFOJwJ8ERdknLPMO" crossorigin="anonymous">-->
<!--        <link rel="stylesheet" type="text/css" href="jquery.numberKeypad.css">-->
<!--        <script type="text/javascript" src="http://code.jquery.com/jquery-1.11.0.min.js"></script>-->
<!--        <script type="text/javascript" src="jquery.numberKeypad.js"></script>-->
<!--      키패드 cdn 끝-->




  </head>
<title>대진산업_전자발주</title>
  <body>
  <!-- 네비게이션바 -->

    <nav class="navbar navbar-expand-lg navbar-dark bg-success border-bottom" style="height:5%">
        <div class="container-sm">
            <div>
            <a class="navbar-brand" href="{% url 'eos:index' %}" accesskey="j" onMouseOver="this.innerHTML='alt+j'" onMouseOut="this.innerHTML='EOS'">Eos</a>
<!--            <a class="navbar-brand" href="{% url 'eos:order_page' %}" accesskey="w" onMouseOver="this.innerHTML='alt+w'" onMouseOut="this.innerHTML='발주작성'">발주작성</a>-->
            <a class="navbar-brand" href="{% url 'eos:order_create' %}" accesskey="w" onMouseOver="this.innerHTML='alt+w'" onMouseOut="this.innerHTML='write'">write</a>
<!--            <a class="navbar-brand" href="{% url 'eos:product' %}" accesskey="p" onMouseOver="this.innerHTML='alt+p'" onMouseOut="this.innerHTML='상품관리'">상품관리</a>-->
            </div>
          <div class="navbar-collapse collapse justify-content-end" id="navbarSupportedContent">

        </div>

       </div>


    </nav>

  <!-- 기본 템플릿 안에 삽입될 내용 Start -->
  {% block content %}
  {% endblock %}
  <!-- 기본 템플릿 안에 삽입될 내용 End -->

  <!-- 자바스크립트 Start -->
  {% block script %}
  {% endblock %}
  <!-- 자바스크립트 End -->

<!--  <script>-->
<!--      const searchInput = document.getElementById("search_kw");-->
<!--      const maxLength = 50;-->

<!--      searchInput.addEventListener("focus", e => {-->
<!--      const el = e.target;-->
<!--      setTimeout(() => {-->
<!--        el.setSelectionRange(maxLength, maxLength);-->
<!--        el.scrollLeft = maxLength * 30;-->
<!--        }, 0);-->
<!--      });-->
<!--  </script>-->
  </body>


</html>

templates/navbar.html
<!-- 네비게이션바 -->
<nav class="navbar navbar-expand-lg navbar-dark bg-dark border-bottom">
    <a class="navbar-brand" href="{% url 'pybo:index' %}">DaeJin</a>
    <button class="navbar-toggler ml-auto" type="button" data-toggle="collapse" data-target="#navbarNav"
        aria-controls="navbarNav" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
    </button>
    <div class="collapse navbar-collapse flex-grow-0" id="navbarNav">
        <ul class="navbar-nav">
            <li class="nav-item ">
                {% if user.is_authenticated %}
                <a class="nav-link" href="{% url 'common:logout' %}">{{ user.username }} (로그아웃)</a>
                {% else %}
                <a class="nav-link" href="{% url 'common:login' %}">로그인</a>
                {% endif %}
            </li>
        </ul>
    </div>
</nav>