config/urls.py
from django.contrib import admin
from django.urls import path, include
from pybo.views import base_views
from django.conf import settings
from django.conf.urls.static import static


urlpatterns = [
    path('admin/', admin.site.urls),
    path('pybo/', include('pybo.urls')),
    # path('paystub/', include('paystub.urls')),
    path('common/', include('common.urls')),
    path('polls/', include('polls.urls')),
    path('eas/', include('eas.urls')),
    path('pybo/', base_views.index),
    path('', include('polls.urls')),
    path('eos/', include('eos.urls')),
    path('cart/', include('cart.urls')),
    # 👉 전자 품의서
    path('approval/', include('approvals.urls')),
    
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

eas/urls.py
# eas/urls.py
from django.urls import path
from . import views
from django.conf.urls.static import static
from django.conf import settings

app_name = "eas"

urlpatterns = [
    path("", views.index, name="index"),
    path("<int:Request_id>/", views.detail, name="detail_r"),

    # (주의) detail은 Request_id 인자가 필요한 detail 뷰와 시그니처가 안 맞을 수 있어.
    # 필요 없으면 지우는 걸 추천. 일단 유지하려면 detail 뷰를 따로 만들거나 URL을 없애야 함.
    # path("detail", views.detail, name="detail"),

    path("Request/create/", views.Request_create, name="Request_create"),
    path("Request/create_24/", views.Request_create_24, name="Request_create_24"),
    path("Request/create/sangsin/<int:new_Request_id>/", views.Request_create_sangsin, name="Request_create_sangsin"),

    path("detail/update/<int:new_Request_id>/", views.detail_update, name="detail_update"),
    path("detail/okupdate/<int:new_Request_id>/", views.detail_okupdate, name="detail_okupdate"),
    path("detail/update2/<int:new_Request_id>/", views.detail_update2, name="detail_update2"),
    path("detail/okupdate2/<int:new_Request_id>/", views.detail_okupdate2, name="detail_okupdate2"),

    path("detail_modify/<int:new_Request_id>/", views.Request_modify, name="Request_modify"),

    path("monthly_holiday/", views.monthly_holiday, name="monthly_holiday"),
    path("monthly_holiday_r/<int:Request_id>/", views.monthly_holiday_r, name="monthly_holiday_r"),
    path("monthly_holiday_r/okupdate2/<int:new_Request_id>/", views.monthly_holiday_r_okupdate2, name="monthly_holiday_r_okupdate2"),
    path("monthly_holiday_r/update2/<int:new_Request_id>/", views.monthly_holiday_r_update2, name="monthly_holiday_r_update2"),

    path("account.html/", views.account, name="account"),

    path("nomal_approval/", views.nomal_approval, name="nomal_approval"),
    path("nomal_approval_r/<int:Request_id>/", views.nomal_approval_r, name="nomal_approval_r"),

    path("ds.html/", views.ds, name="ds"),

    # ✅ 자동완성 API
    path("api/vendor-suggest/", views.vendor_suggest, name="vendor_suggest"),
]

urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

eos/urls.py
from django.urls import path
from . import views
from django.conf.urls.static import static
from django.conf import settings
from .views import ProductView

app_name = 'eos'

urlpatterns = [
    path('', views.index, name='index'),
    path('<int:Order_list_id>/', views.order_page, name='order_page'),
    path('<int:User_id>/', views.order_page, name='order_page'),
    path('product/', ProductView.as_view(), name='product'),
    path('p_list/', views.p_list),
    path('order_page/', views.order_page, name='order_page'),
    path('order_create/', views.order_create, name='order_create'),
    path('order_create/searchData/', views.searchData, name='searchData'),

]

eos/models.py
from django.db import models
import jsonfield


class Products(models.Model):
    objects = models.Manager()
    p_id = models.IntegerField(blank=True, null=True, verbose_name='상품코드')
    org_bar = models.IntegerField(blank=True, null=True, verbose_name='원코드')
    sale_bar = models.IntegerField(blank=True, null=True, verbose_name='판매코드')
    p_name = models.CharField(max_length=200, blank=True, verbose_name='상품명')
    iq = models.IntegerField(blank=True, null=True, verbose_name='입수')
    p_price = models.IntegerField(blank=True, null=True, verbose_name='출고가')
    location = models.CharField(max_length=200, blank=True, verbose_name='위치정보')

    def __str__(self):
        return self.p_name

    # class Meta:
    #     db_table = 'midas_Products'
    #     verbose_name = '상품'
    #     verbose_name_plural = '상품'





class Order_list(models.Model):
    odp_name = models.CharField(max_length=200, blank=True)  # 발주자명
    buyer_name = models.CharField(max_length=200, blank=True)  # 수주자명
    phon_num = models.CharField(max_length=200, blank=True)  # 전화번호
    od_count = models.IntegerField(blank=True, null=True) #낱개발주수량
    od_box_count = models.IntegerField(blank=True, null=True) #박스발주수량
    d_day = models.DateTimeField(blank=True) #배송요청일
    od_date = models.DateTimeField(blank=True, null=True) #발주일(today)
    del_check = models.CharField(max_length=200, blank=True) #미출체크(발주삭제)
    order_note = models.TextField(blank=True) #발주자 기타사항
    out_note = models.TextField(blank=True) #수주자 기타사항
    note = models.TextField(blank=True) #기타사항(공지사항)
    total_sum = models.IntegerField(blank=True, null=True) #발주합계금액
    img1 = models.ImageField(blank=True)
    img2 = models.ImageField(blank=True)
    img3 = models.ImageField(blank=True)
    aaa = models.CharField(max_length=200, blank=True) #바이어네임 씽크
    bbb = models.CharField(max_length=200, blank=True) #상품명
    ccc = models.CharField(max_length=200, blank=True)
    ddd = models.CharField(max_length=200, blank=True)
    eee = models.CharField(max_length=200, blank=True)
    fff = models.IntegerField(blank=True, null=True)
    ggg = models.IntegerField(blank=True, null=True)
    hhh = models.IntegerField(blank=True, null=True)
    s_product = models.CharField(max_length=200, blank=True)
    s_iq = models.IntegerField(blank=True, null=True)
    s_price = models.IntegerField(blank=True, null=True)
    s_location = models.CharField(max_length=200, blank=True)
    s_org_bar = models.IntegerField(blank=True, null=True)
    upload = models.FileField(upload_to='uploads/', blank=True, null=True)
    od_list = jsonfield.JSONField(default='{}', blank=True, null=True)

    def __str__(self):
        return self.buyer_name

eos/forms.py
from django import forms
from eos.models import Order_list
from cart.models import CartItem

class Order_listForm(forms.ModelForm):
    class Meta:
        model = Order_list  # 사용할 모델
        fields = ['od_count', 'od_box_count', 'd_day', 'od_date',
                  'del_check', 'order_note', 'out_note', 'note',
                  'total_sum', 'img1', 'img2', 'img3', 'aaa',
                  'bbb', 'ccc', 'ddd', 'eee', 'fff', 'ggg', 'hhh', 'upload',
                  'buyer_name', 'odp_name', 'phon_num', 'od_list', 's_iq',
                  's_price', 's_location', 's_org_bar']

eos/views.py
from django.core.paginator import Paginator
from django.core.serializers.json import DjangoJSONEncoder
from django.http import HttpResponse
from django.utils import timezone
from django.shortcuts import render, get_object_or_404, redirect
from django.views.decorators.csrf import csrf_exempt
from django.views.generic import ListView
from django.db.models import Q
from .forms import Order_listForm
from .models import Products
from .models import Order_list
from django.core.exceptions import ObjectDoesNotExist
import csv
import pandas as pd
from django.contrib import messages
import json
from django.http import JsonResponse
from cart.models import Cart, CartItem


def index(request):
    page = request.GET.get('page', '1')  # 페이지
    kw = request.GET.get('kw', '')  # 검색어
    Order_lists = Order_list.objects.order_by('-od_date')
    if kw:
        Order_lists = Order_lists.filter(
            Q(buyer_name__icontains=kw) |  #
            # Q(d_day__icontains=kw) |  #
            # Q(od_date__icontains=kw) |
            Q(p_name__icontains=kw)
            # Q(sale_bar__icontains=kw) |
            # Q(org_bar__icontains=kw)
        ).distinct()
    # context = {'Order_lists': Order_lists}
    paginator = Paginator(Order_lists, 10)  # 페이지당 10개씩 보여주기
    page_obj = paginator.get_page(page)
    context = {'Order_lists': page_obj, 'page': page, 'kw': kw}
    return render(request, 'eos/index.html', context)


# def order_page(request):
#     return render(request, 'eos/order_page.html')

class ProductView(ListView):
    model = Products
    template_name = 'eos/product.html'


# 상품db 업데이트
def p_list(request):
    with open("/home/ubuntu/projects/mysite/static/p_list.csv", "r", encoding='cp949') as f:
        dr = csv.DictReader(f)
        s = pd.DataFrame(dr)
    ss = []
    for i in range(len(s)):
        # st = (s["ID"][i], s["상품명"][i], s["바코드"][i], s["입수"][i], s["납품가"][i], s["원코드"][i], s["위치정보"][i])
        Products.objects.create(p_id=s["ID"][i],
                                p_name=s["상품명"][i],
                                sale_bar=s["바코드"][i],
                                iq=s["입수"][i],
                                p_price=s["납품가"][i],
                                org_bar=s["원코드"][i],
                                location=s["위치정보"][i])



def order_page(request, Order_list_id):
    new_order_list = get_object_or_404(Order_list, pk=Order_list_id)
    context = {'new_order_list': new_order_list}
    return render(request, 'eos/order_page_r.html', context)



# 기존 order_create--------------------------------
def order_create(request):
    if request.method == 'POST':
        form = Order_listForm(request.POST)
        if form.is_valid():
            new_order_list = form.save(commit=False)
            new_order_list.od_date = timezone.now()
            input_cal = request.POST.get('calender')
            new_order_list.d_day = input_cal
            input_buyer = request.POST.get('buyer_select')
            new_order_list.buyer_name = input_buyer
            # jsonfield save
            data = request.POST.getlist('input[]')
            new_order_list.od_list = data

            # Product Class 조회 변수 저장
            psb = Products.objects.get(sale_bar=(new_order_list.od_list[0]))
            new_order_list.s_product = psb.p_name
            new_order_list.s_iq = psb.iq
            new_order_list.s_price = psb.p_price
            new_order_list.s_location = psb.location
            new_order_list.s_org_bar = psb.org_bar
            new_order_list.save()

            context = {'new_order_list': new_order_list}
            return render(request, 'eos/order_page_r.html', context)
        else:
            context = {'form': form}
            return render(request, 'eos/order_page.html', context)
    else:
        form = Order_listForm()
        context = {'form': form}
        return render(request, 'eos/order_page.html', context)
# 기존 order_create--------------------------------






def some_function(request):
    messages.error(request, "발주매장 선택하세요")
    # order_create(request)
# 메시지 팝업
# def some_function(request):
#     messages.warning(request, "낱개발주와 박스발주 같이 입력하면 낱개발주 0 으로 됨.")



@csrf_exempt
def searchData(request):
    # POST 요청일 때
    if 'searchwords' in request.POST:
        data = request.POST['searchwords']
        s_data = Products.objects.get(sale_bar=(data))
        s_p_name = s_data.p_name
        s_p_iq = s_data.iq
        s_p_price = s_data.p_price
        s_p_location = s_data.location
        s_p_org_bar = s_data.org_bar

        context = {
            'result': s_p_name,
            'result_iq': s_p_iq,
            'result_price': s_p_price,
            'result_location': s_p_location,
            'result_org_bar': s_p_org_bar,
        }

        return JsonResponse(context)

eos/templates/eos/index.html
{% extends 'base_eos.html' %}
{% block content %}
{% load eos_filter %}

<div class="container my-3">
    <div class="row justify-content-between">
        <div class="col-lg-7 col-md-2 d-none d-sm-block"></div>
        <div class="col-lg-3 col-sm-5">
            <!--        검색창-->
            <!--                <form class="d-flex justify-content-end" id="search">-->
            <div class="input-group">
                <input hidden="hidden"/>
                <input type="text" id="search_kw" class="form-control me-2" accesskey="a"
                       value="{{ kw|default_if_none:'' }}" placeholder="alt+a">
                <div class="input-group-append">
                    <button class="btn btn-outline-secondary" type="button" id="btn_search">Search</button>
                </div>
            </div>
            <!--                </form>-->
        </div>
        <div class="col-1"></div>
    </div>


    <!--    <div class="container my-3">-->
    <!--        <div class="row my-3">-->
    <!--            <div class="col-6">-->

    <!--            </div>-->
    <!--            <div class="col-6">-->
    <!--                <div class="input-group">-->
    <!--                    <input type="text" id="search_kw" class="form-control" value="{{ kw|default_if_none:'' }}">-->
    <!--                    <div class="input-group-append">-->
    <!--                        <button class="btn btn-outline-secondary" type="button" id="btn_search">Search</button>-->
    <!--                    </div>-->
    <!--                </div>-->
    <!--            </div>-->
    <!--        </div>-->
    <!--    </div>-->
    <div class="row justify-content-between my-3">
        <div class="col-1 d-none d-sm-block"></div>
        <div class="col-lg-9 col-md-12 col-sm-12">
            <table class="table table-hover table table-bordered border-secondary">
                <thead>
                <tr class="table-success text-center ">
                    <th>No</th>

                    <th style="width:52%">발주매장</th>
                    <th style="width:8%">발주일</th>
                    <th style="width:8%">배송일</th>
                    <th style="width:8%">발주자</th>
                    <th>&nbsp;&nbsp;미출체크</th>
                </tr>
                </thead>
                <tbody>

                {% if Order_lists %}
                {% for Order_list in Order_lists %}
                <tr class="text-center">
                    <td>
                        <!-- 번호 = 전체건수 - 시작인덱스 - 현재인덱스 + 1 -->
                        {{ Order_lists.paginator.count|sub:Order_lists.start_index|sub:forloop.counter0|add:1 }}
                    </td>

                    <td class="text-start" style="font-color:#000000">
                        <a href="/eos/{{ Order_list.id }}/" style="text-decoration:none">{{Order_list.buyer_name }} </a>
                    </td>
                    <td style="text-align:right;">{{ Order_list.od_date|date:'y-n-d' }}</td>
                    <td style="text-align:right;">{{ Order_list.d_day|date:'y-n-d' }}</td>
                    <td> &nbsp;&nbsp;</td>
                </tr>
                {% endfor %}

                {% else %}
                <tr>
                    <p>발주 리스트가 없습니다.</p>
                </tr>
                {% endif %}

                </tbody>
            </table>
            <!-- 페이징처리 시작 -->
            <ul class="pagination justify-content-center">
                <!-- 이전페이지 -->
                {% if Order_lists.has_previous %}
                <li class="page-item">
                    <a class="page-link" data-page="{{ Order_lists.previous_page_number }}"
                       href="javascript:void(0)">이전</a>
                </li>
                {% else %}
                <li class="page-item disabled">
                    <a class="page-link" tabindex="-1" aria-disabled="true" href="javascript:void(0)">이전</a>
                </li>
                {% endif %}
                <!-- 페이지리스트 -->
                {% for page_number in Order_lists.paginator.page_range %}
                {% if page_number >= Order_lists.number|add:-5 and page_number <= Order_lists.number|add:5 %}
                {% if page_number == Order_lists.number %}
                <li class="page-item active" aria-current="page">
                    <a class="page-link" data-page="{{ page_number }}" href="javascript:void(0)">{{ page_number }}</a>
                </li>
                {% else %}
                <li class="page-item">
                    <a class="page-link" data-page="{{ page_number }}" href="javascript:void(0)">{{ page_number }}</a>
                </li>
                {% endif %}
                {% endif %}
                {% endfor %}
                <!-- 다음페이지 -->
                {% if Order_lists.has_next %}
                <li class="page-item">
                    <a class="page-link" data-page="{{ Order_lists.next_page_number }}" href="javascript:void(0)">다음</a>
                </li>
                {% else %}
                <li class="page-item disabled">
                    <a class="page-link" tabindex="-1" aria-disabled="true" href="javascript:void(0)">다음</a>
                </li>
                {% endif %}
            </ul>
        </div>
        <div class="col-1 d-none d-sm-block"></div>
    </div>
    <!--    <p></p>-->
    <!--&lt;!&ndash;    랜덤 이미지 &ndash;&gt;-->
    <!--    <table align="center">-->
    <!--        <tr align="center" >-->
    <!--            <td><img src="https://picsum.photos/1080/620/?random" class="img-fluid img-thumbnail"></td>-->
    <!--        </tr>-->
    <!--    </table>-->

</div>
<!-- 페이징처리 끝 -->


<!-- 검색 -->
<form id="searchForm" method="get" action="{% url 'eos:index' %}">
    <input type="hidden" id="kw" name="kw" value="{{ kw|default_if_none:'' }}">
    <input type="hidden" id="page" name="page" value="{{ page }}">
</form>


<script src="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/js/bootstrap.bundle.min.js"
        integrity="sha384-ka7Sk0Gln4gmtz2MlQnikT1wXgYsOg+OMhuP+IlRH9sENBO0LRn5q+8nbTov4+1p"
        crossorigin="anonymous"></script>
<!--    <ul>-->
<!--      <a href="{% url 'eas:Request_create' %}" class="btn btn-secondary">작성하기</a>-->
<!--    </ul>-->
{% endblock %}
{% block script %}
<script type='text/javascript'>
    const page_elements = document.getElementsByClassName("page-link");
    Array.from(page_elements).forEach(function(element) {
        element.addEventListener('click', function() {
            document.getElementById('page').value = this.dataset.page;
            document.getElementById('searchForm').submit();
        });
    });
    const btn_search = document.getElementById("btn_search");
    btn_search.addEventListener('click', function() {
        document.getElementById('kw').value = document.getElementById('search_kw').value;
        document.getElementById('page').value = 1;  // 검색버튼을 클릭할 경우 1페이지부터 조회한다.
        document.getElementById('searchForm').submit();
    });

    function enterkey() {
            if (window.event.keyCode == 13) {
                 $("#search").submit();
            }
        }


const searchInput = document.getElementById("search_kw");
const maxLength = 50;

    searchInput.addEventListener("focus", e => {
    const el = e.target;
    setTimeout(() => {
        el.setSelectionRange(maxLength, maxLength);
        el.scrollLeft = maxLength * 30;
        }, 0);
    });


</script>
{% endblock %}

eos/templates/eos/order_page.html
{% extends 'base_eos.html' %}
{% block content %}
{% load humanize %}

{% if messages %}
<ul class="absoulte top-0 right-0 left-0 flex justify-center">
    {% for message in messages %}
    <li class="z-20 message py-3 px-5 text-white rounded-lg font-bold text-lg {% if message.tags %} {{ message.tags }}{% endif %}">
        {{ message }}
    </li>
    {% endfor %}
</ul>
{% endif %}

<p></p>
<div class="container">
    <form method="post" name="order_create" onkeydown="return event.key != 'Enter';">
<!--    <form method="post" name="order_create">-->
        {% csrf_token %}
        <!-- 오류표시 Start -->
        {% if form.errors %}
        <div class="alert alert-danger" role="alert">
            {% for field in form %}
            {% if field.errors %}
            <div>
                <strong>{{ field.label }}</strong>
                {{ field.errors }}
            </div>
            {% endif %}
            {% endfor %}
        </div>
        {% endif %}
        <!-- 오류표시 End -->


        <div class="row">
            <div class="col-3">
                <span>발주자 : 오더리스트 발주페이지</span>
            </div>
            <div class="col-5">
                <span>발주일 :
                   <script>
                    date = new Date().toLocaleDateString();
                    document.write(date);
                    </script>
                </span>
            </div>
            <div class="col-lg-4 col-md-4 col-sm-4 d-none d-sm-block">
                <button type="button" class="btn btn-outline-dark">파일생성</button>
                <button type="button" class="btn btn-outline-dark">발주서 출력</button>
                <button type="submit" class="btn-outline-dark" id="order_submit">전송</button>
            </div>

        </div>
        <br>
        <!--        <div class="row">-->
        <!--           <div>-->
        <!--            <table background="/static/img/dark_wood.png" width="100%"  height="30">-->
        <!--                <tr>-->
        <!--                    <td></td>-->
        <!--                </tr>-->
        <!--            </table>-->
        <!--          </div>-->
        <!--&lt;!&ndash;            <div style="" ><img src="/static/img/dark_wood.png"> </div>&ndash;&gt;-->
        <!--        </div>-->
        <span style="line-height:50%"><br></span>

        <div class="row input-group">

            <div class="col-lg-4 col-md-4 col-sm-12 input-group">
                <span class="input-group-text">발주매장</span>
                <select class="form-select" aria-label="Default select example" name="buyer_select" id="buyerselect" value="{{ form.buyerselect.value|default_if_none:'' }}">
                    <option selected></option>
                    <option value="북단양농협하나로마트'">북단양농협하나로마트'</option>
                    <option value="단양농협하나로마트'">단양농협하나로마트'</option>
                    <option value="단양소백하나로마트'">단양소백하나로마트'</option>
                    <option value="대강하나로마트'">대강하나로마트'</option>
                    <option value="상진농협하나로마트'">상진농협하나로마트'</option>
                    <option value="봉양농협하나로마트'">봉양농협하나로마트'</option>
                    <option value="남제천농협하나로마트'">남제천농협하나로마트'</option>
                    <option value="남제천농협 청풍지점'">남제천농협 청풍지점'</option>
                    <option value="가곡농협하나로마트'">가곡농협하나로마트'</option>
                </select>

                <!--  배송일 달력 날짜선택   -->
                <span class="input-group-text">배송일</span>
                <!--          <div class="col-lg-4 col-md-4 col-sm-12">-->

                <input type="text" name="calender" inputmode="none" placeholder="배송일" id="date-picker"
                       class="form-control bg-white border-1 small" aria-label="Search" aria-describedby="basic-addon2" value="{{ form.d_day.value|default_if_none:'' }}">
                <!--            <input type="text" inputmode="none" id="date-picker" class="form-control bg-white border-1 small" aria-label="Search" aria-describedby="basic-addon2" th:value="|${year}-${month}-${day}|">-->
            </div>
            <p></p>
        </div>

        <div class="row bg-Secondary" align="center" style="margin-left: 2px; margin-right: 1px">
            <div class="col-lg-1 col-md-2 col-sm-2 d-none d-sm-block text-white" align="center">no</div>
            <div class="col-lg-2 col-md-2 col-sm-2  text-white" align="center">바코드</div>
            <div class="col-lg-2 col-md-2 col-sm-2  text-white" align="center">상품명</div>
            <div class="col-lg-1 col-md-1 col-sm-1 d-none d-sm-block  text-white" align="center">입수</div>
            <div class="col-lg-1 col-md-1 col-sm-1  text-white" align="center">발주</div>
            <div class="col-lg-1 col-md-1 col-sm-1  text-white" align="center">박스발주</div>
            <div class="col-lg-1 col-md-1 col-sm-1 d-none d-sm-block  text-white" align="center">단가</div>
            <div class="col-lg-1 col-md-1 col-sm-1 d-none d-sm-block  text-white" align="center">위치</div>
            <div class="col-lg-1 col-md-1 col-sm-1 d-none d-sm-block  text-white" align="center">원바코드</div>
            <div class="col-lg-1 col-md-1 col-sm-1 d-none d-sm-block  text-white" align="center">체크</div>
        </div>

        <span style="line-height:50%"><br></span>
        <div class="row">
            <div class="col-lg-1" align="center"> 1
            </div>
            <div class="col-lg-2" id="search" align="center">
                <input type="number"  name="input[]" pattern="\d*" id="searchword"
                       value="{{ form.od_list.0.value|default_if_none:'' }}" onkeydown = "if(event.keyCode==13) move_textbox();">
            </div>
            <div class="col-lg-2" id="results" align="center"> <!-- 상품명 -->
            </div>
            <div class="col-lg-1" id="results_iq" align="center"> <!-- 입수 -->
            </div>
            <div class="col-lg-1">
                <input type="number" id="test_obj" pattern="\d*"  name="input[]" class="form-control input-sm" value="{{ form.od_list.1.value|default_if_none:'' }}">
            </div>
            <div class="col-lg-1">
                <input type="number" id="test_obj1" pattern="\d*" name="input[]" class="form-control input-sm" value="{{ form.od_list.2.value|default_if_none:'' }}">
            </div>
            <div class="col-lg-1" id="results_price" align="center"> <!-- 단가 -->
            </div>
            <div class="col-lg-1" id="results_location" align="center"> <!-- 위치 -->
            </div>
            <div class="col-lg-1" id="results_org_bar" align="center"> <!-- 원코드 -->
            </div>
            <div class="col-lg-1" align="center"> <!-- 체크 -->
                <span> </span>
            </div>

        </div>

        <hr>
        <p></p>


    </form>
</div>


<script>

$(function() {
  $( "#date-picker" ).datepicker({
    dateFormat: 'yy-mm-dd'
  });
});



$(document).ready(function(){
        searchajax();
});


<!--ajax-->
function searchajax(){
$('#searchword').keyup(function() {
    inputdata = $('#searchword').val();
    if( inputdata != ''){
        $.ajax({
            url:'{% url 'eos:searchData' %}',
            type:'POST',
            data: { searchwords : inputdata },
            dataType: 'json',
            success: function(result){
<!--                if ( result.length > 0){-->
                    var str = ''
                    var str_iq = ''
                    var str_price =''
                    var str_location =''
                    var str_org_bar =''
<!--                    for (var i=0; i<result.length; i++){-->
                    JSON.stringify(result)
                    str += '<span>'+ result.result + '</span><br/>';

<!--                    }-->
                    $("#results").html(str);
                    str_iq += '<span>'+ result.result_iq + '</span><br/>';
                    $("#results_iq").html(str_iq);

                    str_price += '<span>'+ result.result_price + '</span><br/>';
                    $("#results_price").html(str_price);

                    str_location += '<span>'+ result.result_location + '</span><br/>';
                    $("#results_location").html(str_location);

                    str_org_bar += '<span>'+ result.result_org_bar + '</span><br/>';
                    $("#results_org_bar").html(str_org_bar);




                    console.log('ajax success')
                    console.log(result)
<!--                }-->
<!--                    else{ $("#results").html(str); }-->
            },
            error: function(e) {console.log('오류:' + e.status);}
        });
    }  else{ $("#results").html(""); }
  });
}


<!--&lt;!&ndash;ajax&ndash;&gt;-->
<!--function searchajax(){-->
<!--$('#searchword').keyup(function() {-->
<!--    data = $('#searchword').val();-->
<!--    if( data != ''){-->
<!--        $.ajax({-->
<!--            url:'{% url 'eos:searchData' %}',-->
<!--            type:'POST',-->
<!--            headers: {-->
<!--                'X-CSRFTOKEN' : '{{ csrf_token }}'-->
<!--            },-->
<!--            data:JSON.stringify(data),-->
<!--            success:function(json){-->
<!--                console.log("data pass success",json);-->
<!--            },-->
<!--            error : function(xhr,errmsg,err) {-->
<!--            console.log(xhr.status + ": " + xhr.responseText);-->
<!--            console.log("어디가 틀린겨?");-->
<!--            }-->
<!--        });-->
<!--    }-->
<!--  });-->
<!--}-->




</script>





{% endblock %}

eos/templates/eos/product.html
{% extends 'base_eos.html' %}
{% block content %}
{% load eos_filter %}
{% load humanize %}

<div class = "container my-3">

    <table class="table table-striped">
      <thead>
        <tr class="table-secondary">
          <th scope="col">#</th>
          <th scope="col">상품코드</th>
          <th scope="col">상품명</th>
          <th scope="col">바코드</th>
          <th scope="col">입수</th>
          <th scope="col">출고가</th>
          <th scope="col">위치정보</th>
          <th scope="col">원바코드</th>
        </tr>
      </thead>
      <tbody>
      {% for Products in object_list %}
        <tr>
          <th scope="row">{{Products.id}}</th>
          <td>{{Products.p_id}}</td>
          <td>{{Products.p_name}}</td>
          <td>{{Products.sale_bar}}</td>
          <td>{{Products.iq}}</td>
          <td>{{Products.p_price|intcomma}}</td>
          <td>{{Products.location}}</td>
          <td>{{Products.org_bar}}</td>
        </tr>
      {% endfor %}
      </tbody>
    </table>



</div>
{% endblock %}